title: Abiyselassie Gashaw
#logo:"/image/logo.png?raw=true" # your photo (or logo) here
![alt text](image.jpg)
# Data Science Portfolio <br>
<a href="https://www.linkedin.com/in/abiyselassiegashaw/">View My LinkedIn Profile</a> 
show_downloads:false
theme:jekyll-theme-minimal
